### ISSUE TITLE
Players attack command issues

### ISSUE THREAD

**Issue by mushyp3a** [Cjsah/mixit#6]
The fake player's attack command very inconsistently works and the fake players sometimes deal no damage to mobs.

**Comment by Cjsah** [comment]
This version is too old and is going to be migrated by the latest fabric-carpet
If that happens, it will be fixed

**Comment by mushyp3a** [comment]
Ah ok, do you know roughly when it might be migrated by the latest fabric-carpet?

**Comment by Cjsah** [comment]
All code has been ported
We are testing that all features work

**Comment by mushyp3a** [comment]
Ah great, so an update should be soon then? If you need help with testing - I could try and help report any bugs etc if you need

**Comment by Cjsah** [comment]
Yeah. The main problem at present is that it can only run in the development environment, and most of the other problems have been solved
If you want to help us, you can clone the latest code to run and test

**Comment by mushyp3a** [comment]
Ok cool, will do

**Comment by mushyp3a** [comment]
![image](https://user-images.githubusercontent.com/30042290/183880543-15e7aa5c-8556-4bb2-b146-3088364c6dcc.png)
I received this error when running gradlew build and then when  I moved the .jar file in and ran forge 1.18.2 40.1.0 I got exit code 1. Am I building the mod wrong? (I ran "gradlew build" in the directory)

**Comment by Cjsah** [comment]
You need remove `src/main/resources/carpet.refmap.json`. But jar compiled by running gradlew build does not start properly.
Currently only runs through the development environment
Run `gradlew genIntellijRuns`(Intellij IDEA) or `gradlew genEclipseRuns`(Eclipse) in your ide to generate the development runtime environment to  run it

**Comment by mushyp3a** [comment]
Ok thank you, I've got it working now and so far all the commands seem functional in different use cases and so far haven't caused any lag spikes or drops in frames. I'll let you know if I find anything but this is really very impressive. Do you have any idea how long it will be until the jar is released (I assume there is no way for me to compile it myself)

**Comment by Cjsah** [comment]
The mod is now working properly in production environment

**Comment by mushyp3a** [comment]
Thank you so much, it is setup now on a server and having no problems at all.

**Comment by Cjsah** [comment]
Okey, thank you for your test
